stages: 
  #- test
  - build 
  - test
  - testFront
  - testBack
  # - deploy

# test project:
#   stage: test
#   image: node:16
#   script:
#     - npm install
#     # - npm start

build project:
  stage: build
  image: node:16-alpine
  script:
    - npm install
  #   - npm run build
  # artifacts:
  #   paths:
  #     - build

test website:
  image: alpine
  stage: test
  script:
    - test build/index.html

test front:
  image: alpine
  stage: testFront
  script:
    - test src/app.js

test back:
  image: alpine
  stage: testBack
  script:
    - test server/server.js



# netlify:
#   stage: deploy
#   image: node:14
#   script:
#     - npm install -g netlify-cli
#     - netlify deploy --dir=build --prod
    